# -*- coding: utf-8 -*-
"""Copy of Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mOY3tciGA0rSRxMvTa9r-FaxId9oTsZ4
"""

!pip install tensorflow-gpu

import tensorflow as tf
print(tf.__version__)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset=pd.read_csv("Churn_Modelling.csv")
dataset.head()

